/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/assets/dungeon/scenario1.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scenario1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={materials['Stone(Clone)']} />
      <mesh geometry={nodes.mesh_0_1.geometry} material={materials['StoneDark(Clone)']} />
      <mesh geometry={nodes.mesh_0_2.geometry} material={materials['BrownDark(Clone)']} />
      <mesh geometry={nodes.mesh_0_3.geometry} material={materials['PurpleDark(Clone)']} />
      <mesh geometry={nodes.mesh_0_4.geometry} material={materials['White(Clone)']} />
      <mesh geometry={nodes.mesh_0_5.geometry} material={materials['Metal(Clone)']} />
      <mesh geometry={nodes.mesh_0_6.geometry} material={materials['BlueDark(Clone)']} />
      <mesh geometry={nodes.mesh_0_7.geometry} material={materials['GreenDark(Clone)']} />
      <mesh geometry={nodes.mesh_0_8.geometry} material={materials['WoodDark(Clone)']} />
      <mesh geometry={nodes.mesh_0_9.geometry} material={materials['Black(Clone)']} />
      <mesh geometry={nodes.mesh_0_10.geometry} material={materials['Gold(Clone)']} />
      <mesh geometry={nodes.mesh_0_11.geometry} material={materials['Beige(Clone)']} />
    </group>
  )
}

useGLTF.preload('/scenario1.glb')
